//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 10:43:37 PM CET 
//


package eu.fbk.dkm.pikes.resources.util.fnlu;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for annotationSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="annotationSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="layer" type="{http://framenet.icsi.berkeley.edu}layerType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://framenet.icsi.berkeley.edu}IDType" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="frameName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="frameID" type="{http://framenet.icsi.berkeley.edu}IDType" />
 *       &lt;attribute name="luName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="luID" type="{http://framenet.icsi.berkeley.edu}IDType" />
 *       &lt;attribute name="cxnName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cxnID" type="{http://framenet.icsi.berkeley.edu}IDType" />
 *       &lt;attribute name="cDate" type="{http://framenet.icsi.berkeley.edu}dateTimeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "annotationSetType", propOrder = {
    "layer"
})
public class AnnotationSetType {

    @XmlElement(required = true)
    protected List<LayerType> layer;
    @XmlAttribute(name = "ID")
    protected Integer id;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "frameName")
    protected String frameName;
    @XmlAttribute(name = "frameID")
    protected Integer frameID;
    @XmlAttribute(name = "luName")
    protected String luName;
    @XmlAttribute(name = "luID")
    protected Integer luID;
    @XmlAttribute(name = "cxnName")
    protected String cxnName;
    @XmlAttribute(name = "cxnID")
    protected Integer cxnID;
    @XmlAttribute(name = "cDate")
    protected String cDate;

    /**
     * Gets the value of the layer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LayerType }
     * 
     * 
     */
    public List<LayerType> getLayer() {
        if (layer == null) {
            layer = new ArrayList<LayerType>();
        }
        return this.layer;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setID(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the frameName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameName() {
        return frameName;
    }

    /**
     * Sets the value of the frameName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameName(String value) {
        this.frameName = value;
    }

    /**
     * Gets the value of the frameID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFrameID() {
        return frameID;
    }

    /**
     * Sets the value of the frameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFrameID(Integer value) {
        this.frameID = value;
    }

    /**
     * Gets the value of the luName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLuName() {
        return luName;
    }

    /**
     * Sets the value of the luName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLuName(String value) {
        this.luName = value;
    }

    /**
     * Gets the value of the luID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLuID() {
        return luID;
    }

    /**
     * Sets the value of the luID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLuID(Integer value) {
        this.luID = value;
    }

    /**
     * Gets the value of the cxnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCxnName() {
        return cxnName;
    }

    /**
     * Sets the value of the cxnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCxnName(String value) {
        this.cxnName = value;
    }

    /**
     * Gets the value of the cxnID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCxnID() {
        return cxnID;
    }

    /**
     * Sets the value of the cxnID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCxnID(Integer value) {
        this.cxnID = value;
    }

    /**
     * Gets the value of the cDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDate() {
        return cDate;
    }

    /**
     * Sets the value of the cDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDate(String value) {
        this.cDate = value;
    }

}
