//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 10:43:37 PM CET 
//


package eu.fbk.dkm.pikes.resources.util.fnlu;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FEGroupRealizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FEGroupRealizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FE" type="{http://framenet.icsi.berkeley.edu}FEValenceType" maxOccurs="unbounded"/>
 *         &lt;element name="pattern" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="valenceUnit" type="{http://framenet.icsi.berkeley.edu}valenceUnitType" maxOccurs="unbounded"/>
 *                   &lt;element name="annoSet" type="{http://framenet.icsi.berkeley.edu}annoSetType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="total" use="required" type="{http://framenet.icsi.berkeley.edu}countType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="total" use="required" type="{http://framenet.icsi.berkeley.edu}countType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FEGroupRealizationType", propOrder = {
    "fe",
    "pattern"
})
public class FEGroupRealizationType {

    @XmlElement(name = "FE", required = true)
    protected List<FEValenceType> fe;
    @XmlElement(required = true)
    protected List<FEGroupRealizationType.Pattern> pattern;
    @XmlAttribute(name = "total", required = true)
    protected int total;

    /**
     * Gets the value of the fe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FEValenceType }
     * 
     * 
     */
    public List<FEValenceType> getFE() {
        if (fe == null) {
            fe = new ArrayList<FEValenceType>();
        }
        return this.fe;
    }

    /**
     * Gets the value of the pattern property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pattern property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPattern().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FEGroupRealizationType.Pattern }
     * 
     * 
     */
    public List<FEGroupRealizationType.Pattern> getPattern() {
        if (pattern == null) {
            pattern = new ArrayList<FEGroupRealizationType.Pattern>();
        }
        return this.pattern;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public int getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(int value) {
        this.total = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="valenceUnit" type="{http://framenet.icsi.berkeley.edu}valenceUnitType" maxOccurs="unbounded"/>
     *         &lt;element name="annoSet" type="{http://framenet.icsi.berkeley.edu}annoSetType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="total" use="required" type="{http://framenet.icsi.berkeley.edu}countType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "valenceUnit",
        "annoSet"
    })
    public static class Pattern {

        @XmlElement(required = true)
        protected List<ValenceUnitType> valenceUnit;
        @XmlElement(required = true)
        protected List<AnnoSetType> annoSet;
        @XmlAttribute(name = "total", required = true)
        protected int total;

        /**
         * Gets the value of the valenceUnit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the valenceUnit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValenceUnit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ValenceUnitType }
         * 
         * 
         */
        public List<ValenceUnitType> getValenceUnit() {
            if (valenceUnit == null) {
                valenceUnit = new ArrayList<ValenceUnitType>();
            }
            return this.valenceUnit;
        }

        /**
         * Gets the value of the annoSet property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the annoSet property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnnoSet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnnoSetType }
         * 
         * 
         */
        public List<AnnoSetType> getAnnoSet() {
            if (annoSet == null) {
                annoSet = new ArrayList<AnnoSetType>();
            }
            return this.annoSet;
        }

        /**
         * Gets the value of the total property.
         * 
         */
        public int getTotal() {
            return total;
        }

        /**
         * Sets the value of the total property.
         * 
         */
        public void setTotal(int value) {
            this.total = value;
        }

    }

}
