//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 10:43:37 PM CET 
//


package eu.fbk.dkm.pikes.resources.util.fnlu;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://framenet.icsi.berkeley.edu}headerType"/>
 *         &lt;element name="definition" type="{http://framenet.icsi.berkeley.edu}defType"/>
 *         &lt;element name="lexeme" type="{http://framenet.icsi.berkeley.edu}lexemeType" maxOccurs="unbounded"/>
 *         &lt;element name="semType" type="{http://framenet.icsi.berkeley.edu}semTypeRefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="valences" type="{http://framenet.icsi.berkeley.edu}valencesType" minOccurs="0"/>
 *         &lt;element name="subCorpus" type="{http://framenet.icsi.berkeley.edu}subCorpusType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://framenet.icsi.berkeley.edu}frameReference"/>
 *       &lt;attGroup ref="{http://framenet.icsi.berkeley.edu}basicLUAttributes"/>
 *       &lt;attribute name="totalAnnotated" type="{http://framenet.icsi.berkeley.edu}countType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "definition",
    "lexeme",
    "semType",
    "valences",
    "subCorpus"
})
@XmlRootElement(name = "lexUnit")
public class LexUnit {

    @XmlElement(required = true)
    protected HeaderType header;
    @XmlElement(required = true)
    protected String definition;
    @XmlElement(required = true)
    protected List<LexemeType> lexeme;
    protected List<SemTypeRefType> semType;
    protected ValencesType valences;
    protected List<SubCorpusType> subCorpus;
    @XmlAttribute(name = "totalAnnotated")
    protected Integer totalAnnotated;
    @XmlAttribute(name = "frameID")
    protected Integer frameID;
    @XmlAttribute(name = "frame")
    protected String frame;
    @XmlAttribute(name = "ID", required = true)
    protected int id;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "POS", required = true)
    protected POSType pos;
    @XmlAttribute(name = "incorporatedFE")
    protected String incorporatedFE;
    @XmlAttribute(name = "status")
    protected String status;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinition(String value) {
        this.definition = value;
    }

    /**
     * Gets the value of the lexeme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lexeme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLexeme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LexemeType }
     * 
     * 
     */
    public List<LexemeType> getLexeme() {
        if (lexeme == null) {
            lexeme = new ArrayList<LexemeType>();
        }
        return this.lexeme;
    }

    /**
     * Gets the value of the semType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the semType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSemType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SemTypeRefType }
     * 
     * 
     */
    public List<SemTypeRefType> getSemType() {
        if (semType == null) {
            semType = new ArrayList<SemTypeRefType>();
        }
        return this.semType;
    }

    /**
     * Gets the value of the valences property.
     * 
     * @return
     *     possible object is
     *     {@link ValencesType }
     *     
     */
    public ValencesType getValences() {
        return valences;
    }

    /**
     * Sets the value of the valences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValencesType }
     *     
     */
    public void setValences(ValencesType value) {
        this.valences = value;
    }

    /**
     * Gets the value of the subCorpus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subCorpus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubCorpus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubCorpusType }
     * 
     * 
     */
    public List<SubCorpusType> getSubCorpus() {
        if (subCorpus == null) {
            subCorpus = new ArrayList<SubCorpusType>();
        }
        return this.subCorpus;
    }

    /**
     * Gets the value of the totalAnnotated property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalAnnotated() {
        return totalAnnotated;
    }

    /**
     * Sets the value of the totalAnnotated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalAnnotated(Integer value) {
        this.totalAnnotated = value;
    }

    /**
     * Gets the value of the frameID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFrameID() {
        return frameID;
    }

    /**
     * Sets the value of the frameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFrameID(Integer value) {
        this.frameID = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrame(String value) {
        this.frame = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link POSType }
     *     
     */
    public POSType getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSType }
     *     
     */
    public void setPOS(POSType value) {
        this.pos = value;
    }

    /**
     * Gets the value of the incorporatedFE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncorporatedFE() {
        return incorporatedFE;
    }

    /**
     * Sets the value of the incorporatedFE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncorporatedFE(String value) {
        this.incorporatedFE = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
