//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 10:43:37 PM CET 
//


package eu.fbk.dkm.pikes.resources.util.fnlu;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fbk.dkm.pikes.resources.util.fnlu package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fbk.dkm.pikes.resources.util.fnlu
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CorpDocType }
     * 
     */
    public CorpDocType createCorpDocType() {
        return new CorpDocType();
    }

    /**
     * Create an instance of {@link FEGroupRealizationType }
     * 
     */
    public FEGroupRealizationType createFEGroupRealizationType() {
        return new FEGroupRealizationType();
    }

    /**
     * Create an instance of {@link FERealizationType }
     * 
     */
    public FERealizationType createFERealizationType() {
        return new FERealizationType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link HeaderType.Frame }
     * 
     */
    public HeaderType.Frame createHeaderTypeFrame() {
        return new HeaderType.Frame();
    }

    /**
     * Create an instance of {@link LexUnit }
     * 
     */
    public LexUnit createLexUnit() {
        return new LexUnit();
    }

    /**
     * Create an instance of {@link LexemeType }
     * 
     */
    public LexemeType createLexemeType() {
        return new LexemeType();
    }

    /**
     * Create an instance of {@link SemTypeRefType }
     * 
     */
    public SemTypeRefType createSemTypeRefType() {
        return new SemTypeRefType();
    }

    /**
     * Create an instance of {@link ValencesType }
     * 
     */
    public ValencesType createValencesType() {
        return new ValencesType();
    }

    /**
     * Create an instance of {@link SubCorpusType }
     * 
     */
    public SubCorpusType createSubCorpusType() {
        return new SubCorpusType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link GovernorType }
     * 
     */
    public GovernorType createGovernorType() {
        return new GovernorType();
    }

    /**
     * Create an instance of {@link FEValenceType }
     * 
     */
    public FEValenceType createFEValenceType() {
        return new FEValenceType();
    }

    /**
     * Create an instance of {@link LayerType }
     * 
     */
    public LayerType createLayerType() {
        return new LayerType();
    }

    /**
     * Create an instance of {@link AnnoSetType }
     * 
     */
    public AnnoSetType createAnnoSetType() {
        return new AnnoSetType();
    }

    /**
     * Create an instance of {@link AnnotationSetType }
     * 
     */
    public AnnotationSetType createAnnotationSetType() {
        return new AnnotationSetType();
    }

    /**
     * Create an instance of {@link ValenceUnitType }
     * 
     */
    public ValenceUnitType createValenceUnitType() {
        return new ValenceUnitType();
    }

    /**
     * Create an instance of {@link SentenceType }
     * 
     */
    public SentenceType createSentenceType() {
        return new SentenceType();
    }

    /**
     * Create an instance of {@link CorpDocType.Document }
     * 
     */
    public CorpDocType.Document createCorpDocTypeDocument() {
        return new CorpDocType.Document();
    }

    /**
     * Create an instance of {@link FEGroupRealizationType.Pattern }
     * 
     */
    public FEGroupRealizationType.Pattern createFEGroupRealizationTypePattern() {
        return new FEGroupRealizationType.Pattern();
    }

    /**
     * Create an instance of {@link FERealizationType.Pattern }
     * 
     */
    public FERealizationType.Pattern createFERealizationTypePattern() {
        return new FERealizationType.Pattern();
    }

    /**
     * Create an instance of {@link HeaderType.Frame.FE }
     * 
     */
    public HeaderType.Frame.FE createHeaderTypeFrameFE() {
        return new HeaderType.Frame.FE();
    }

}
