//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 10:43:37 PM CET 
//


package eu.fbk.dkm.pikes.resources.util.fnlu;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POSType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="POSType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="V"/>
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="ADV"/>
 *     &lt;enumeration value="PRON"/>
 *     &lt;enumeration value="PREP"/>
 *     &lt;enumeration value="NUM"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="INTJ"/>
 *     &lt;enumeration value="ART"/>
 *     &lt;enumeration value="SCON"/>
 *     &lt;enumeration value="CCON"/>
 *     &lt;enumeration value="AVP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "POSType")
@XmlEnum
public enum POSType {

    N,
    V,
    A,
    ADV,
    PRON,
    PREP,
    NUM,
    C,
    INTJ,
    ART,
    SCON,
    CCON,
    AVP;

    public String value() {
        return name();
    }

    public static POSType fromValue(String v) {
        return valueOf(v);
    }

}
