//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 10:43:37 PM CET 
//


package eu.fbk.dkm.pikes.resources.util.fnlu;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for valencesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="valencesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="governor" type="{http://framenet.icsi.berkeley.edu}governorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FERealization" type="{http://framenet.icsi.berkeley.edu}FERealizationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FEGroupRealization" type="{http://framenet.icsi.berkeley.edu}FEGroupRealizationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "valencesType", propOrder = {
    "governor",
    "feRealization",
    "feGroupRealization"
})
public class ValencesType {

    protected List<GovernorType> governor;
    @XmlElement(name = "FERealization")
    protected List<FERealizationType> feRealization;
    @XmlElement(name = "FEGroupRealization")
    protected List<FEGroupRealizationType> feGroupRealization;

    /**
     * Gets the value of the governor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the governor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGovernor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GovernorType }
     * 
     * 
     */
    public List<GovernorType> getGovernor() {
        if (governor == null) {
            governor = new ArrayList<GovernorType>();
        }
        return this.governor;
    }

    /**
     * Gets the value of the feRealization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feRealization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFERealization().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FERealizationType }
     * 
     * 
     */
    public List<FERealizationType> getFERealization() {
        if (feRealization == null) {
            feRealization = new ArrayList<FERealizationType>();
        }
        return this.feRealization;
    }

    /**
     * Gets the value of the feGroupRealization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feGroupRealization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFEGroupRealization().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FEGroupRealizationType }
     * 
     * 
     */
    public List<FEGroupRealizationType> getFEGroupRealization() {
        if (feGroupRealization == null) {
            feGroupRealization = new ArrayList<FEGroupRealizationType>();
        }
        return this.feGroupRealization;
    }

}
