//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.13 at 05:16:47 PM CET 
//


package eu.fbk.dkm.pikes.resources.util.semlink.vnpb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "role")
public class Role {

    @XmlAttribute(name = "pb-arg", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pbArg;
    @XmlAttribute(name = "vn-theta", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String vnTheta;
    @XmlValue
    protected String value;

    /**
     * Gets the value of the pbArg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPbArg() {
        return pbArg;
    }

    /**
     * Sets the value of the pbArg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPbArg(String value) {
        this.pbArg = value;
    }

    /**
     * Gets the value of the vnTheta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnTheta() {
        return vnTheta;
    }

    /**
     * Sets the value of the vnTheta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnTheta(String value) {
        this.vnTheta = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getvalue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setvalue(String value) {
        this.value = value;
    }

}
