//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.13 at 04:07:35 PM CET 
//


package eu.fbk.dkm.pikes.resources.util.semlink.vnfnroles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "role")
public class Role {

    @XmlAttribute(name = "fnrole", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fnrole;
    @XmlAttribute(name = "vnrole", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String vnrole;
    @XmlValue
    protected String value;

    /**
     * Gets the value of the fnrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFnrole() {
        return fnrole;
    }

    /**
     * Sets the value of the fnrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFnrole(String value) {
        this.fnrole = value;
    }

    /**
     * Gets the value of the vnrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnrole() {
        return vnrole;
    }

    /**
     * Sets the value of the vnrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnrole(String value) {
        this.vnrole = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getvalue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setvalue(String value) {
        this.value = value;
    }

}
