#!/bin/bash

# prepare-ontologies
#
# Merges RDF files of ontologies under src/main/owl and computes OWL2RL inferences,
# placing the result in src/main/resources/eu/fbk/dkm/pikes/rdf/rules/RuleDistiller.ontology.ttl
#
# Usage: 'prepare-ontologies <path-to-pikes-rdf-git-folder>'

input=$1
 
[ -z $1 ] && echo "No path to pikes-rdf git folder specified" && exit 1
[ ! -e $input ] && echo "Unable to locate $1" && exit 1

command -v rdfpro >/dev/null 2>&1 || { echo >&2 "Cannot find RDFpro on the machine. Aborting."; exit 1; }

echo "Generating closed ontology"
rdfpro @read "$1"/src/main/owl/* \
       @transform '-o owl:Thing owl:topDataProperty owl:topObjectProperty' \
       @rules -r "$1"/prepare-ontologies.rules.ttl -u -C \
       @write "$1"/src/main/resources/eu/fbk/dkm/pikes/rdf/rules/RuleDistiller.data.ttl
