//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 11:03:16 AM CEST 
//

package eu.fbk.dkm.pikes.tintop.ita.token_old;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tokenizer }
     */
    public Tokenizer createTokenizer() {
        return new Tokenizer();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules }
     */
    public Tokenizer.SplittingRules createTokenizerSplittingRules() {
        return new Tokenizer.SplittingRules();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.CharSplitter }
     */
    public Tokenizer.SplittingRules.CharSplitter createTokenizerSplittingRulesCharSplitter() {
        return new Tokenizer.SplittingRules.CharSplitter();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.CharSplitter.LanguageRest }
     */
    public Tokenizer.SplittingRules.CharSplitter.LanguageRest createTokenizerSplittingRulesCharSplitterLanguageRest() {
        return new Tokenizer.SplittingRules.CharSplitter.LanguageRest();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.CharSplitter.GeneralRules }
     */
    public Tokenizer.SplittingRules.CharSplitter.GeneralRules createTokenizerSplittingRulesCharSplitterGeneralRules() {
        return new Tokenizer.SplittingRules.CharSplitter.GeneralRules();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.KnownWordsList }
     */
    public Tokenizer.SplittingRules.KnownWordsList createTokenizerSplittingRulesKnownWordsList() {
        return new Tokenizer.SplittingRules.KnownWordsList();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.KnownWordsList.LanguageRes }
     */
    public Tokenizer.SplittingRules.KnownWordsList.LanguageRes createTokenizerSplittingRulesKnownWordsListLanguageRes() {
        return new Tokenizer.SplittingRules.KnownWordsList.LanguageRes();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.GeneralSplittingRules }
     */
    public Tokenizer.SplittingRules.GeneralSplittingRules createTokenizerSplittingRulesGeneralSplittingRules() {
        return new Tokenizer.SplittingRules.GeneralSplittingRules();
    }

    /**
     * Create an instance of {@link Tokenizer.Languages }
     */
    public Tokenizer.Languages createTokenizerLanguages() {
        return new Tokenizer.Languages();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.CharSplitter.LanguageRest.Char }
     */
    public Tokenizer.SplittingRules.CharSplitter.LanguageRest.Char createTokenizerSplittingRulesCharSplitterLanguageRestChar() {
        return new Tokenizer.SplittingRules.CharSplitter.LanguageRest.Char();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.CharSplitter.GeneralRules.Char }
     */
    public Tokenizer.SplittingRules.CharSplitter.GeneralRules.Char createTokenizerSplittingRulesCharSplitterGeneralRulesChar() {
        return new Tokenizer.SplittingRules.CharSplitter.GeneralRules.Char();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.KnownWordsList.LanguageRes.Expression }
     */
    public Tokenizer.SplittingRules.KnownWordsList.LanguageRes.Expression createTokenizerSplittingRulesKnownWordsListLanguageResExpression() {
        return new Tokenizer.SplittingRules.KnownWordsList.LanguageRes.Expression();
    }

    /**
     * Create an instance of {@link Tokenizer.SplittingRules.GeneralSplittingRules.Char }
     */
    public Tokenizer.SplittingRules.GeneralSplittingRules.Char createTokenizerSplittingRulesGeneralSplittingRulesChar() {
        return new Tokenizer.SplittingRules.GeneralSplittingRules.Char();
    }

    /**
     * Create an instance of {@link Tokenizer.Languages.Language }
     */
    public Tokenizer.Languages.Language createTokenizerLanguagesLanguage() {
        return new Tokenizer.Languages.Language();
    }

    /**
     * Create an instance of {@link Tokenizer.EndSentenceChars }
     */
    public Tokenizer.EndSentenceChars createTokenizerEndSentenceChars() {
        return new Tokenizer.EndSentenceChars();
    }

    /**
     * Create an instance of {@link Tokenizer.EndSentenceChars.LanguageRes }
     */
    public Tokenizer.EndSentenceChars.LanguageRes createTokenizerEndSentenceCharsLanguageRes() {
        return new Tokenizer.EndSentenceChars.LanguageRes();
    }

    /**
     * Create an instance of {@link Tokenizer.AbbreviationList }
     */
    public Tokenizer.AbbreviationList createTokenizerAbbreviationList() {
        return new Tokenizer.AbbreviationList();
    }

    /**
     * Create an instance of {@link Tokenizer.AbbreviationList.LanguageRes }
     */
    public Tokenizer.AbbreviationList.LanguageRes createTokenizerAbbreviationListLanguageRes() {
        return new Tokenizer.AbbreviationList.LanguageRes();
    }

    /**
     * Create an instance of {@link Tokenizer.EndSentenceChars.LanguageRes.Expression }
     */
    public Tokenizer.EndSentenceChars.LanguageRes.Expression createTokenizerEndSentenceCharsLanguageResExpression() {
        return new Tokenizer.EndSentenceChars.LanguageRes.Expression();
    }

    /**
     * Create an instance of {@link Tokenizer.EndSentenceChars.LanguageRes.Char }
     */
    public Tokenizer.EndSentenceChars.LanguageRes.Char createTokenizerEndSentenceCharsLanguageResChar() {
        return new Tokenizer.EndSentenceChars.LanguageRes.Char();
    }

    /**
     * Create an instance of {@link Tokenizer.AbbreviationList.LanguageRes.Expression }
     */
    public Tokenizer.AbbreviationList.LanguageRes.Expression createTokenizerAbbreviationListLanguageResExpression() {
        return new Tokenizer.AbbreviationList.LanguageRes.Expression();
    }

}