//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 11:03:16 AM CEST 
//

package eu.fbk.dkm.pikes.tintop.ita.token_old;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.BitSet;
import java.util.Iterator;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="languages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="language" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                           &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="splittingRules" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="generalSplittingRules" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="char" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="knownWordsList" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="languageRes" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="expression" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                               &lt;attribute name="replaceTo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="charSplitter" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="generalRules" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="char" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                               &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="languageRest" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="char" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                               &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "languages",
        "splittingRules",
        "abbreviationList",
        "endSentenceChars"
})
@XmlRootElement(name = "tokenizer")
public class Tokenizer {

    protected Tokenizer.Languages languages;
    protected Tokenizer.SplittingRules splittingRules;
    protected Tokenizer.AbbreviationList abbreviationList;
    protected Tokenizer.EndSentenceChars endSentenceChars;

    /**
     * Gets the value of the languages property.
     *
     * @return possible object is
     * {@link Tokenizer.Languages }
     */
    public Tokenizer.Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     *
     * @param value allowed object is
     *              {@link Tokenizer.Languages }
     */
    public void setLanguages(Tokenizer.Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the splittingRules property.
     *
     * @return possible object is
     * {@link Tokenizer.SplittingRules }
     */
    public Tokenizer.SplittingRules getSplittingRules() {
        return splittingRules;
    }

    /**
     * Sets the value of the splittingRules property.
     *
     * @param value allowed object is
     *              {@link Tokenizer.SplittingRules }
     */
    public void setSplittingRules(Tokenizer.SplittingRules value) {
        this.splittingRules = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="language" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                 &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "language"
    })
    public static class Languages {

        @XmlElement(required = true)
        protected List<Tokenizer.Languages.Language> language;

        /**
         * Gets the value of the language property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tokenizer.Languages.Language }
         */
        public List<Tokenizer.Languages.Language> getLanguage() {
            if (language == null) {
                language = new ArrayList<Tokenizer.Languages.Language>();
            }
            return this.language;
        }

        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         */

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "id"
        })
        public static class Language {

            @XmlAttribute(name = "id", required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String id;

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setId(String value) {
                this.id = value;
            }
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="generalSplittingRules" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="char" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="knownWordsList" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="languageRes" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="expression" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                                     &lt;attribute name="replaceTo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="charSplitter" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="generalRules" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="char" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="languageRest" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="char" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "generalSplittingRules",
            "knownWordsList",
            "charSplitter"
    })
    public static class SplittingRules {

        protected Tokenizer.SplittingRules.GeneralSplittingRules generalSplittingRules;
        protected Tokenizer.SplittingRules.KnownWordsList knownWordsList;
        protected Tokenizer.SplittingRules.CharSplitter charSplitter;

        /**
         * Gets the value of the generalSplittingRules property.
         *
         * @return possible object is
         * {@link Tokenizer.SplittingRules.GeneralSplittingRules }
         */
        public Tokenizer.SplittingRules.GeneralSplittingRules getGeneralSplittingRules() {
            return generalSplittingRules;
        }

        /**
         * Sets the value of the generalSplittingRules property.
         *
         * @param value allowed object is
         *              {@link Tokenizer.SplittingRules.GeneralSplittingRules }
         */
        public void setGeneralSplittingRules(Tokenizer.SplittingRules.GeneralSplittingRules value) {
            this.generalSplittingRules = value;
        }

        /**
         * Gets the value of the knownWordsList property.
         *
         * @return possible object is
         * {@link Tokenizer.SplittingRules.KnownWordsList }
         */
        public Tokenizer.SplittingRules.KnownWordsList getKnownWordsList() {
            return knownWordsList;
        }

        /**
         * Sets the value of the knownWordsList property.
         *
         * @param value allowed object is
         *              {@link Tokenizer.SplittingRules.KnownWordsList }
         */
        public void setKnownWordsList(Tokenizer.SplittingRules.KnownWordsList value) {
            this.knownWordsList = value;
        }

        /**
         * Gets the value of the charSplitter property.
         *
         * @return possible object is
         * {@link Tokenizer.SplittingRules.CharSplitter }
         */
        public Tokenizer.SplittingRules.CharSplitter getCharSplitter() {
            return charSplitter;
        }

        /**
         * Sets the value of the charSplitter property.
         *
         * @param value allowed object is
         *              {@link Tokenizer.SplittingRules.CharSplitter }
         */
        public void setCharSplitter(Tokenizer.SplittingRules.CharSplitter value) {
            this.charSplitter = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="generalRules" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="char" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="languageRest" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="char" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "generalRules",
                "languageRest"
        })
        public static class CharSplitter {

            protected Tokenizer.SplittingRules.CharSplitter.GeneralRules generalRules;
            @XmlElement(required = true)
            protected List<Tokenizer.SplittingRules.CharSplitter.LanguageRest> languageRest;

            /**
             * Gets the value of the generalRules property.
             *
             * @return possible object is
             * {@link Tokenizer.SplittingRules.CharSplitter.GeneralRules }
             */
            public Tokenizer.SplittingRules.CharSplitter.GeneralRules getGeneralRules() {
                return generalRules;
            }

            /**
             * Sets the value of the generalRules property.
             *
             * @param value allowed object is
             *              {@link Tokenizer.SplittingRules.CharSplitter.GeneralRules }
             */
            public void setGeneralRules(Tokenizer.SplittingRules.CharSplitter.GeneralRules value) {
                this.generalRules = value;
            }

            /**
             * Gets the value of the languageRest property.
             * <p>
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the languageRest property.
             * <p>
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLanguageRest().add(newItem);
             * </pre>
             * <p>
             * <p>
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Tokenizer.SplittingRules.CharSplitter.LanguageRest }
             */
            public List<Tokenizer.SplittingRules.CharSplitter.LanguageRest> getLanguageRest() {
                if (languageRest == null) {
                    languageRest = new ArrayList<Tokenizer.SplittingRules.CharSplitter.LanguageRest>();
                }
                return this.languageRest;
            }

            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="char" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "_char"
            })
            public static class GeneralRules {

                @XmlElement(name = "char", required = true)
                protected List<Tokenizer.SplittingRules.CharSplitter.GeneralRules.Char> _char;

                /**
                 * Gets the value of the char property.
                 * <p>
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the char property.
                 * <p>
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getChar().add(newItem);
                 * </pre>
                 * <p>
                 * <p>
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Tokenizer.SplittingRules.CharSplitter.GeneralRules.Char }
                 */
                public List<Tokenizer.SplittingRules.CharSplitter.GeneralRules.Char> getChar() {
                    if (_char == null) {
                        _char = new ArrayList<Tokenizer.SplittingRules.CharSplitter.GeneralRules.Char>();
                    }
                    return this._char;
                }

                public BitSet getCharIds() {
                    BitSet ids = new BitSet();
                    Iterator<Char> chrl = this.getChar().iterator();
                    while (chrl.hasNext()) {
                        Char chrtmp = chrl.next();
                        ids.set(chrtmp.getId());
                    }

                    return ids;
                }

                /**
                 * <p>Java class for anonymous complex type.
                 * <p>
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * <p>
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
                 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "value"
                })
                public static class Char {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "id", required = true)
                    protected int id;
                    @XmlAttribute(name = "hexcode", required = true)
                    protected String hexcode;
                    @XmlAttribute(name = "desc", required = false)
                    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                    @XmlSchemaType(name = "normalizedString")
                    protected String desc;

                    /**
                     * Gets the value of the value property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the id property.
                     */
                    public int getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     */
                    public void setId(int value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the hexcode property.
                     */
                    public String getHexcode() {
                        return hexcode;
                    }

                    /**
                     * Sets the value of the hexcode property.
                     */
                    public void setHexcode(String value) {
                        this.hexcode = value;
                    }

                    /**
                     * Gets the value of the name property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getDesc() {
                        return desc;
                    }

                    /**
                     * Sets the value of the name property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setDesc(String value) {
                        this.desc = value;
                    }

                }

            }

            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="char" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "_char"
            })
            public static class LanguageRest {

                @XmlElement(name = "char", required = true)
                protected List<Tokenizer.SplittingRules.CharSplitter.LanguageRest.Char> _char;
                @XmlAttribute(name = "id", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String id;

                /**
                 * Gets the value of the char property.
                 * <p>
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the char property.
                 * <p>
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getChar().add(newItem);
                 * </pre>
                 * <p>
                 * <p>
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Tokenizer.SplittingRules.CharSplitter.LanguageRest.Char }
                 */
                public List<Tokenizer.SplittingRules.CharSplitter.LanguageRest.Char> getChar() {
                    if (_char == null) {
                        _char = new ArrayList<Tokenizer.SplittingRules.CharSplitter.LanguageRest.Char>();
                    }
                    return this._char;
                }

                /**
                 * Gets the value of the id property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * <p>Java class for anonymous complex type.
                 * <p>
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * <p>
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
                 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "value"
                })
                public static class Char {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "id", required = true)
                    protected int id;
                    @XmlAttribute(name = "hexcode", required = true)
                    protected String hexcode;
                    @XmlAttribute(name = "desc", required = false)
                    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                    @XmlSchemaType(name = "normalizedString")
                    protected String desc;

                    /**
                     * Gets the value of the value property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the id property.
                     */
                    public int getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     */
                    public void setId(int value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the hexcode property.
                     */
                    public String getHexcode() {
                        return hexcode;
                    }

                    /**
                     * Sets the value of the hexcode property.
                     */
                    public void setHexcode(String value) {
                        this.hexcode = value;
                    }

                    /**
                     * Gets the value of the name property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getDesc() {
                        return desc;
                    }

                    /**
                     * Sets the value of the name property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setDesc(String value) {
                        this.desc = value;
                    }

                }

            }

        }

        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="char" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "_char"
        })
        public static class GeneralSplittingRules {

            @XmlElement(name = "char", required = true)
            protected List<Tokenizer.SplittingRules.GeneralSplittingRules.Char> _char;

            /**
             * Gets the value of the char property.
             * <p>
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the char property.
             * <p>
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getChar().add(newItem);
             * </pre>
             * <p>
             * <p>
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Tokenizer.SplittingRules.GeneralSplittingRules.Char }
             */
            public List<Tokenizer.SplittingRules.GeneralSplittingRules.Char> getChar() {
                if (_char == null) {
                    _char = new ArrayList<Tokenizer.SplittingRules.GeneralSplittingRules.Char>();
                }
                return this._char;
            }

            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "value"
            })
            public static class Char {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "id", required = true)
                protected int id;
                @XmlAttribute(name = "hexcode", required = true)
                protected String hexcode;
                @XmlAttribute(name = "desc", required = false)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String desc;

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the id property.
                 */
                public int getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 */
                public void setId(int value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the hexcode property.
                 */
                public String getHexcode() {
                    return hexcode;
                }

                /**
                 * Sets the value of the hexcode property.
                 */
                public void setHexcode(String value) {
                    this.hexcode = value;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getDesc() {
                    return desc;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setDesc(String value) {
                    this.desc = value;
                }

            }

        }

        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="languageRes" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="expression" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *                           &lt;attribute name="replaceTo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "languageRes"
        })
        public static class KnownWordsList {

            @XmlElement(required = true)
            protected List<Tokenizer.SplittingRules.KnownWordsList.LanguageRes> languageRes;

            /**
             * Gets the value of the languageRes property.
             * <p>
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the languageRes property.
             * <p>
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLanguageRes().add(newItem);
             * </pre>
             * <p>
             * <p>
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Tokenizer.SplittingRules.KnownWordsList.LanguageRes }
             */
            public List<Tokenizer.SplittingRules.KnownWordsList.LanguageRes> getLanguageRes() {
                if (languageRes == null) {
                    languageRes = new ArrayList<Tokenizer.SplittingRules.KnownWordsList.LanguageRes>();
                }
                return this.languageRes;
            }

            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="expression" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *                 &lt;attribute name="replaceTo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "expression"
            })
            public static class LanguageRes {

                @XmlElement(required = true)
                protected List<Tokenizer.SplittingRules.KnownWordsList.LanguageRes.Expression> expression;
                @XmlAttribute(name = "id", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String id;

                /**
                 * Gets the value of the expression property.
                 * <p>
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the expression property.
                 * <p>
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getExpression().add(newItem);
                 * </pre>
                 * <p>
                 * <p>
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Tokenizer.SplittingRules.KnownWordsList.LanguageRes.Expression }
                 */
                public List<Tokenizer.SplittingRules.KnownWordsList.LanguageRes.Expression> getExpression() {
                    if (expression == null) {
                        expression = new ArrayList<Tokenizer.SplittingRules.KnownWordsList.LanguageRes.Expression>();
                    }
                    return this.expression;
                }

                /**
                 * Gets the value of the id property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * <p>Java class for anonymous complex type.
                 * <p>
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * <p>
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
                 *       &lt;attribute name="replaceTo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "value"
                })
                public static class Expression {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "name", required = true)
                    protected String name;
                    @XmlAttribute(name = "find", required = true)
                    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                    @XmlSchemaType(name = "normalizedString")
                    protected String find;
                    @XmlAttribute(name = "replaceTo", required = true)
                    protected String replaceTo;

                    /**
                     * Gets the value of the value property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the name property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the find property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getFind() {
                        return find;
                    }

                    /**
                     * Sets the value of the find property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setFind(String value) {
                        this.find = value;
                    }

                    /**
                     * Gets the value of the replaceTo property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getReplaceTo() {
                        return replaceTo;
                    }

                    /**
                     * Sets the value of the replaceTo property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setReplaceTo(String value) {
                        this.replaceTo = value;
                    }

                }

            }

        }

    }

    /**
     * Gets the value of the abbreviationList property.
     *
     * @return possible object is
     * {@link Tokenizer.AbbreviationList }
     */
    public Tokenizer.AbbreviationList getAbbreviationList() {
        return abbreviationList;
    }

    /**
     * Sets the value of the abbreviationList property.
     *
     * @param value allowed object is
     *              {@link Tokenizer.AbbreviationList }
     */
    public void setAbbreviationList(Tokenizer.AbbreviationList value) {
        this.abbreviationList = value;
    }

    /**
     * Gets the value of the ndSentenceChars property.
     *
     * @return possible object is
     * {@link Tokenizer.EndSentenceChars }
     */
    public Tokenizer.EndSentenceChars getEndSentenceChars() {
        return endSentenceChars;
    }

    /**
     * Sets the value of the endSentenceChars property.
     *
     * @param value allowed object is
     *              {@link Tokenizer.EndSentenceChars }
     */
    public void setEndSentenceChars(Tokenizer.EndSentenceChars value) {
        this.endSentenceChars = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="languageRes" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="expression" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="abbreviation" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "languageRes"
    })
    public static class AbbreviationList {

        @XmlElement(required = true)
        protected List<Tokenizer.AbbreviationList.LanguageRes> languageRes;

        /**
         * Gets the value of the languageRes property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the languageRes property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguageRes().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tokenizer.AbbreviationList.LanguageRes }
         */
        public List<Tokenizer.AbbreviationList.LanguageRes> getLanguageRes() {
            if (languageRes == null) {
                languageRes = new ArrayList<Tokenizer.AbbreviationList.LanguageRes>();
            }
            return this.languageRes;
        }

        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="expression" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="abbreviation" type="{http://www.w3.org/2001/XMLSchema}normalizedString" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "expression",
                "abbreviation"
        })
        public static class LanguageRes {

            @XmlElement(required = true)
            protected List<Tokenizer.AbbreviationList.LanguageRes.Expression> expression;
            @XmlElement(required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected List<String> abbreviation;
            @XmlAttribute(name = "id", required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String id;

            /**
             * Gets the value of the expression property.
             * <p>
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the expression property.
             * <p>
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExpression().add(newItem);
             * </pre>
             * <p>
             * <p>
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Tokenizer.AbbreviationList.LanguageRes.Expression }
             */
            public List<Tokenizer.AbbreviationList.LanguageRes.Expression> getExpression() {
                if (expression == null) {
                    expression = new ArrayList<Tokenizer.AbbreviationList.LanguageRes.Expression>();
                }
                return this.expression;
            }

            /**
             * Gets the value of the abbreviation property.
             * <p>
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the abbreviation property.
             * <p>
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAbbreviation().add(newItem);
             * </pre>
             * <p>
             * <p>
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             */
            public List<String> getAbbreviation() {
                if (abbreviation == null) {
                    abbreviation = new ArrayList<String>();
                }
                return this.abbreviation;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "value"
            })
            public static class Expression {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "find", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String find;

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the find property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getFind() {
                    return find;
                }

                /**
                 * Sets the value of the find property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setFind(String value) {
                    this.find = value;
                }

            }

        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="languageRes" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="expression" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="char" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="hexcode" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "languageRes"
    })
    public static class EndSentenceChars {

        @XmlElement(required = true)
        protected List<Tokenizer.EndSentenceChars.LanguageRes> languageRes;

        /**
         * Gets the value of the languageRes property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the languageRes property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguageRes().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tokenizer.EndSentenceChars.LanguageRes }
         */
        public List<Tokenizer.EndSentenceChars.LanguageRes> getLanguageRes() {
            if (languageRes == null) {
                languageRes = new ArrayList<Tokenizer.EndSentenceChars.LanguageRes>();
            }
            return this.languageRes;
        }

        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="expression" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="char" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="hexcode" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "expression",
                "_char"
        })
        public static class LanguageRes {

            @XmlElement(required = true)
            protected List<Tokenizer.EndSentenceChars.LanguageRes.Expression> expression;
            @XmlElement(name = "char", required = true)
            protected List<Tokenizer.EndSentenceChars.LanguageRes.Char> _char;
            @XmlAttribute(name = "id", required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String id;

            /**
             * Gets the value of the expression property.
             * <p>
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the expression property.
             * <p>
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExpression().add(newItem);
             * </pre>
             * <p>
             * <p>
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Tokenizer.EndSentenceChars.LanguageRes.Expression }
             */
            public List<Tokenizer.EndSentenceChars.LanguageRes.Expression> getExpression() {
                if (expression == null) {
                    expression = new ArrayList<Tokenizer.EndSentenceChars.LanguageRes.Expression>();
                }
                return this.expression;
            }

            /**
             * Gets the value of the char property.
             * <p>
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the char property.
             * <p>
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getChar().add(newItem);
             * </pre>
             * <p>
             * <p>
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Tokenizer.EndSentenceChars.LanguageRes.Char }
             */
            public List<Tokenizer.EndSentenceChars.LanguageRes.Char> getChar() {
                if (_char == null) {
                    _char = new ArrayList<Tokenizer.EndSentenceChars.LanguageRes.Char>();
                }
                return this._char;
            }

            /**
             * Gets the value of the id property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="hexcode" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "value"
            })
            public static class Char {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "id", required = true)
                protected int id;
                @XmlAttribute(name = "hexcode", required = true)
                protected String hexcode;
                @XmlAttribute(name = "desc", required = false)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String desc;

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the id property.
                 */
                public int getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 */
                public void setId(int value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the hexcode property.
                 */
                public String getHexcode() {
                    return hexcode;
                }

                /**
                 * Sets the value of the hexcode property.
                 */
                public void setHexcode(String value) {
                    this.hexcode = value;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getDesc() {
                    return desc;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setDesc(String value) {
                    this.desc = value;
                }

            }

            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="find" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "value"
            })
            public static class Expression {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "find", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String find;

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the find property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getFind() {
                    return find;
                }

                /**
                 * Sets the value of the find property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setFind(String value) {
                    this.find = value;
                }

            }

        }

    }

}
